### ISSUE TITLE
Sitewide Header

### ISSUE THREAD

**Issue by vragosta** [vragosta/studiotag#1]
### Sitewide Header Punchlist
- [x] Add similar height treatment that was done on front page header to the expanded menu. Should be a smooth transition.
- [x] Add opacity to menu items ( waiting for @PatrickCenteno to green light this ).
- [x] Add `Contact` back into menu.

### Full Screen
![screen shot 2017-02-25 at 1 19 27 pm](https://cloud.githubusercontent.com/assets/10521070/23333661/23e16d7e-fb5d-11e6-9f32-abab532f1340.png)

### Mobile
![screen shot 2017-02-25 at 1 19 54 pm](https://cloud.githubusercontent.com/assets/10521070/23333662/24a3cb30-fb5d-11e6-86ba-7ecdc9e3e2e9.png)

Pat, I overhauled the HTML, CSS and JS. Lets get on a call so I can explain what I did. I had originally decided to modify your code slightly and mark it in an issue, however it was becoming increasingly time consuming and as I went down that path I realized that I had to give this a complete overhaul.

As you can see from the images above, the desired outcome remained the same. I completed removed all js functionality, everything is now handled in CSS.

Here is a link to the [commit](https://github.com/vragosta/studiotag/commit/046209d47cab44612b41e1db572621727d1f3347) with the changes.

I plan to hit the front page header next, will try approach of not having to overhaul, but in the event I must lets get on another call and talk it through. Please note, i do not plan to overhaul your work by any means, I am hoping that you will intimately look at the changes I have made so you can learn from them for the future layouts you do.

**Comment by vragosta** [comment]
## Analysis Breakdown
Below is a list of all the changes I made to your work.
- There was extraneous HTML, for example
```
<div class="mobile-show">
            <figure>
                <a id="mobile-img-header"></a>
            </figure>

            <div class="mobile-menu">
                <div id="company" class="mobile-menu-catagories">Company</div>
                <div id="company-expand" class="mobile-menu-expand">
                    <a href="#" class="mobile-menu-expand-content">History</a>
                    <a href="#" class="mobile-menu-expand-content">Focus</a>
                    <a href="#" class="mobile-menu-expand-content">Solutions</a>
                    <a href="#" class="mobile-menu-expand-content">Team</a>
                </div>
                <a href="#" id="wall-details" class="mobile-menu-catagories">Wall Details</a>
                <a href="#" id="projects" class="mobile-menu-catagories">Projects</a>
                <a href="#" id="news" class="mobile-menu-catagories">News</a>
            </div>
        </div>
```
While this approach is not incorrect, I was able to optimize the code in such a way where I was able to reuse the existing logo and menu for the mobile screen - eliminating the need for the above code.

I created a modularized menu file:
#### partials/content-menu.php
```
<section class="menu-container">

	<!-- Menu -->
	<ul id="menu">

		<!-- Company will only display at 768px [+] -->
		<li class="dropdown">
			<a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Company</a>
			<ul class="dropdown-menu">
				<li><a href="#">History</a></li>
				<li><a href="#">Focus</a></li>
				<li><a href="#">Solutions</a></li>
				<li><a href="#">Team</a></li>
			</ul>
		</li>

		<!-- Company mobile will only display at 768px [-] -->
		<li class="mobile">
			<a href="#">Company</a>
			<ul class="expand">
				<li><a href="#">History</a></li>
				<li><a href="#">Focus</a></li>
				<li><a href="#">Solutions</a></li>
				<li><a href="#">Team</a></li>
			</ul>
		</li>

		<li><a href="#">Wall Details</a></li>
		<li><a href="#">Projects</a></li>
		<li><a href="#">News</a></li>
	</ul>
</section>
```

As you may notice, there is just different treatment for the `Company` dropdown HTML at the different screen sizes. Otherwise this code is used at full screen and mobile screen.

We are including the file mentioned above with the logo in our header file.
#### partials/content-header-navigation.php
```
<nav class="header-navigation">

	<!-- logo -->
	<section id="logo">
		<a href="<?php echo home_url(); ?>">
			<img src="<?php echo STUDIO_WALL_TEMPLATE_URL . '/assets/images/tagwall-black.png'; ?>" />
		</a>
	</section>

	<!-- Menu -->
	<?php get_template_part( 'partials/content', 'menu' ); ?>

</nav>
```

- Removed all js logic. Similarly to what I had mentioned above, your approach was not wrong however we can handle hover effects in CSS.

Here was your original code:
#### js/studiowall---twenty-seventeen.js
```
	$(".mobile-menu-catagories").hover( function (){
		// Hide everything first
		$(".mobile-menu-expand").css("display", "none");

		$idToShow = "#" + $(this).attr("id") + "-expand";
		// console.log($idToShow);
		$($idToShow).css({"display" : "flex", "flex-direction" : "column"})
	});
```

I was able to optimize it as such:
#### css/studiowall-header---twenty-seventeen.css
```
/*--- Hide the mobile button ---*/
#menu .mobile {
	display: none;
}

/*--- Media Query for mobile button ---*/
@media only screen and ( max-width: 768px ) {
	#menu .mobile {
		display: flex;
		justify-content: center;
		align-items: center;
		flex-direction: column;
	}
}

/*--- Styles to the expanded menu ( when hovering over the mobile button ) ---*/
#menu .expand {
	display: none;
	flex-direction: column;
	justify-content: center;
	align-items: center;
	padding: 0;
}

/*--- Media Query for expanded menu ---*/
@media only screen and ( max-width: 768px ) {
	#menu .mobile:hover .expand {
		display: flex;
	}
}
```

When we hover over the new company button ( which is only displayed at 768px [-] ), we display the expanded menu.

This is basically your exact approach in js, however it is just in CSS.

- I was also able to make use of the new HTML 5 elements. In your code you stuck to `<div>` alot, which again wont be a problem syntactically but when someone else is reading your work, it becomes more readable to diversify your element choice.

- Lastly, and probably most importantly, just comment your code. All HTML, CSS and JS should be commented so that when someone else reads your work, they understand the flow of whats going on, as opposed to someone having to spend time tracing.

@pcenteno, overall this is great work! It comes down to a matter of efficiency which you will develop over time. The only thing I could say as a criticism is just to comment your work more. Otherwise, keep these layouts coming!

**Comment by vragosta** [comment]
+ I also took the flex approach for controlling the header as opposed to bootstrap. The only bootstrap I used was for the dropdown.

Feel free to pushback on any of these items for clarity or if you disagree with any of the approaches.

**Comment by PatrickCenteno** [comment]
@vragosta,

### Requested Changes
- The words in this header must be in all caps. This change is reflected in the site demo [here](https://patrickcenteno.github.io/).

**Comment by vragosta** [comment]
@PatrickCenteno,

I have added `text-transform: uppercase` to all links within the header on this template. Here is a [link](https://github.com/vragosta/studiotag/pull/8) to the PR.

Do we want to consider adding some hover behavior to the link items as well?

Currently there is none. My suggestion is to give a slight opacity on hover. If you want, I can get you a working model of this and you can decide if you like it then. Thoughts?

Thanks!

**Comment by vragosta** [comment]
@PatrickCenteno,

I have added the hover effects to the header and footer. Please let me know what you think.

Thanks!

**Comment by PatrickCenteno** [comment]
@vragosta,

`Contact` link has to be added back in.

**Comment by vragosta** [comment]
@pcenteno,

I have added the `Contact` link back into the header.
