### ISSUE TITLE
Front Page Header

### ISSUE THREAD

**Issue by vragosta** [vragosta/studiotag#2]
### Front Page Header Punchlist
- [x] Address the issue with the spacing between the menu items.
- [x] Add `Contact`back into header.

#### Collapsed Menu
![screen shot 2017-02-26 at 5 04 06 pm](https://cloud.githubusercontent.com/assets/10521070/23344178/c10995c0-fc45-11e6-8a6b-330854677684.png)

#### Expanded Menu w/o hover over first menu item
![screen shot 2017-02-26 at 5 04 10 pm](https://cloud.githubusercontent.com/assets/10521070/23344182/cd671c7a-fc45-11e6-8766-dc98b39cd3a5.png)

#### Expanded Menu w/ hover over first menu item
![screen shot 2017-02-26 at 5 04 13 pm](https://cloud.githubusercontent.com/assets/10521070/23344184/e4f866be-fc45-11e6-8b43-aac4e63e0ff0.png)

<hr />

#### Collapsed Menu
![screen shot 2017-02-26 at 5 04 19 pm](https://cloud.githubusercontent.com/assets/10521070/23344203/17fdbc3a-fc46-11e6-923e-a8f0c4ab575c.png)

#### Expanded Menu w/o hover over first menu item
![screen shot 2017-02-26 at 5 04 22 pm](https://cloud.githubusercontent.com/assets/10521070/23344204/1efa75e6-fc46-11e6-8ae2-4e0791e5d430.png)

#### Expanded Menu w/ hover over first menu item
![screen shot 2017-02-26 at 5 04 23 pm](https://cloud.githubusercontent.com/assets/10521070/23344206/248cbf46-fc46-11e6-9204-0500089f287f.png)

@pcenteno, similarly I had to overhaul the HTML, CSS and JS. This time around we definitely needed the javascript. I was able to reduce the number of classes used in the CSS and was able to reduce the HTML for this segment.

Here is the link to the [Pull Request](https://github.com/vragosta/studiotag/pull/4/commits).

I am going to provide a detailed analysis of the changes made from your work to mine, so stay tuned!

**Comment by vragosta** [comment]
## Analysis Breakdown
Below is a list of changes made to your work.
- Similarly to #1, there was extraneous HTML. This isn't so much of your problem as it is bootstraps. I took a flex approach and did not use the standard bootstrap elements to handle this header.

Here is the entire HTML segment of the new header.
```
<nav class="header-navigation-front-page">

	<!-- Logo -->
	<section id="logo">
		<a href="<?php echo home_url(); ?>">
			<img src="<?php echo STUDIO_WALL_TEMPLATE_URL . '/assets/images/tagwall.png'; ?>" />
		</a>
	</section>

	<button class="hamburger hamburger--squeeze" type="button">
		<span class="hamburger-box">
			<span class="hamburger-inner"></span>
		</span>
	</button>
</nav>

<!-- Menu -->
<section class="menu-container">
	<ul>
		<li><a href="#" data-id="company">Company</a></li>
		<li><a href="#">Wall Details</a></li>
		<li><a href="#">Projects</a></li>
		<li><a href="#">News</a></li>
	</ul>
	<ul>
		<li><a href="#">History</a></li>
		<li><a href="#">Focus</a></li>
		<li><a href="#">Solutions</a></li>
		<li><a href="#">Team</a></li>
	</ul>
</section>
```

You can see we didnt stray too far, but instances of multiple container elements have been reduced. Here is an example of your code that has been simplified to one line in the code above.
#### Full code segment
```
    <div class="overlay">
        <div class="overlay-content">
            <div class="container">
                <div class="catagory-container col-md-6 col-sm-6 col-xs-6">
                    <h1 class="overlay-catagories" id="company">Company</h1>
                    <a href="#"><h1 class="overlay-catagories" id="wall-details">Wall Details</h1></a>
                    <a href="#"><h1 class="overlay-catagories" id="projects">Projects</h1></a>
                    <a href="#"><h1 class="overlay-catagories" id="news">News</h1></a>
                </div>
                <!-- using ID's for all of theses so they can be easily accessed with JS -->
                <div id="list-company" class="hamburger-hover-list col-md-6 col-sm-6 col-xs-6">
                    <a href="#">History</a>
                    <a href="#">Focus</a>
                    <a href="#">Solutions</a>
                    <a href="#">Team</a>
                </div>
            </div>
        </div>
    </div>
```
In particular these three elements have been reduced to one, 
```
    <div class="overlay">
        <div class="overlay-content">
            <div class="container">
```
- Another difference was that I used &lt;ul&gt; and &lt;li&gt; elements instead of &lt;div&gt; and &lt;h1&gt;. If we want to control the font size of an element, its recommended that we do it via the CSS seeing as the semantics of using an &lt;h1&gt; element within a list wouldn't make the most sense here. Here is an example of your code.
```
<div class="catagory-container col-md-6 col-sm-6 col-xs-6">
   <h1 class="overlay-catagories" id="company">Company</h1>
   <a href="#"><h1 class="overlay-catagories" id="wall-details">Wall Details</h1></a>
   <a href="#"><h1 class="overlay-catagories" id="projects">Projects</h1></a>
   <a href="#"><h1 class="overlay-catagories" id="news">News</h1></a>
</div>
```
Here is the revised menu,
```
<ul>
    <li><a href="#" data-id="company">Company</a></li>
    <li><a href="#">Wall Details</a></li>
    <li><a href="#">Projects</a></li>
    <li><a href="#">News</a></li>
</ul>
```
- In the js files, it is considered better practice to use .addClass() instead of .css() to avoid casting inline styles onto an element. Here is your code.
```
$('.overlay').css("height", "100%");
```
Here is the revised code ( with attached CSS ),
```
$( '.menu-container' )
    .removeClass( 'not-visible' )
    .addClass( 'visible' );

/*--- Visible class for use in js ---*/
.menu-container.visible {
	opacity: 1;
	visibility: visible;
	height: 24rem;
}

/*--- Not visible class for use in js ---*/
.menu-container.not-visible {
	opacity: 0;
	visibility: hidden;
	height: 0;
}
```
- One other thing to note, I created a `max-width: 1200px` with `margin: 0 auto;` on the body basically making the entire site constrained to a 1200px width center. You can better see this when we get your local install up and running.

I made this decision because this helps when we collapse the breakpoints since so far we haven't really been using bootstrap.

This is great work we are doing, we are going to get into a rhythm soon.

As always, feel free to pushback on any of this!

**Comment by PatrickCenteno** [comment]
@vragosta,

### Requested Changes
- Add `z-index: 1` and `background-color: #fff`.
- Dropdown must take up entire viewport.

**Comment by vragosta** [comment]
@PatrickCenteno,

I have addressed these items. Here is a [link](https://github.com/vragosta/studiotag/pull/8) to the PR. Do we now want to do something with the spacing in between the menu items?

At the moment it looks like this:
### Full Screen
![screen shot 2017-03-04 at 12 50 41 pm](https://cloud.githubusercontent.com/assets/10521070/23580929/35c1df5c-00d9-11e7-90ce-5067bde6ac30.png)

### Mobile
![screen shot 2017-03-04 at 12 50 31 pm](https://cloud.githubusercontent.com/assets/10521070/23580933/3f19ee46-00d9-11e7-9ff9-3fa89d0d1059.png)

Let me know your thoughts?

**Comment by PatrickCenteno** [comment]
@vragosta,

`Contact` link has to be added back in.
